<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stargate.proto

namespace GPBMetadata;

class Stargate
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Query::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xD6\x02\x0A\x0Estargate.proto\x12\x08stargate2\x8C\x02\x0A\x08Stargate\x125\x0A\x0CExecuteQuery\x12\x0F.stargate.Query\x1A\x12.stargate.Response\"\x00\x12H\x0A\x12ExecuteQueryStream\x12\x0F.stargate.Query\x1A\x1B.stargate.StreamingResponse\"\x00(\x010\x01\x125\x0A\x0CExecuteBatch\x12\x0F.stargate.Batch\x1A\x12.stargate.Response\"\x00\x12H\x0A\x12ExecuteBatchStream\x12\x0F.stargate.Batch\x1A\x1B.stargate.StreamingResponse\"\x00(\x010\x01B#\x0A\x11io.stargate.protoZ\x0Estargate/protob\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

