<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query.proto

namespace Stargate\Batch;

use UnexpectedValueException;

/**
 * Protobuf type <code>stargate.Batch.Type</code>
 */
class Type
{
    /**
     * A logged batch: Cassandra will first write the batch to its distributed batch log to ensure
     * the atomicity of the batch (atomicity meaning that if any statement in the batch succeeds,
     * all will eventually succeed).
     *
     * Generated from protobuf enum <code>LOGGED = 0;</code>
     */
    const LOGGED = 0;
    /**
     * A batch that doesn't use Cassandra's distributed batch log. Such batch are not guaranteed to
     * be atomic.
     *
     * Generated from protobuf enum <code>UNLOGGED = 1;</code>
     */
    const UNLOGGED = 1;
    /**
     * A counter batch. Note that such batch is the only type that can contain counter operations
     * and it can only contain these.
     *
     * Generated from protobuf enum <code>COUNTER = 2;</code>
     */
    const COUNTER = 2;

    private static $valueToName = [
        self::LOGGED => 'LOGGED',
        self::UNLOGGED => 'UNLOGGED',
        self::COUNTER => 'COUNTER',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

