<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query.proto

namespace Stargate\TypeSpec;

use UnexpectedValueException;

/**
 * A CQL primitive type.
 *
 * Protobuf type <code>stargate.TypeSpec.Basic</code>
 */
class Basic
{
    /**
     * Generated from protobuf enum <code>CUSTOM = 0;</code>
     */
    const CUSTOM = 0;
    /**
     * Generated from protobuf enum <code>ASCII = 1;</code>
     */
    const ASCII = 1;
    /**
     * Generated from protobuf enum <code>BIGINT = 2;</code>
     */
    const BIGINT = 2;
    /**
     * Generated from protobuf enum <code>BLOB = 3;</code>
     */
    const BLOB = 3;
    /**
     * Generated from protobuf enum <code>BOOLEAN = 4;</code>
     */
    const BOOLEAN = 4;
    /**
     * Generated from protobuf enum <code>COUNTER = 5;</code>
     */
    const COUNTER = 5;
    /**
     * Generated from protobuf enum <code>DECIMAL = 6;</code>
     */
    const DECIMAL = 6;
    /**
     * Generated from protobuf enum <code>DOUBLE = 7;</code>
     */
    const DOUBLE = 7;
    /**
     * Generated from protobuf enum <code>FLOAT = 8;</code>
     */
    const FLOAT = 8;
    /**
     * Generated from protobuf enum <code>INT = 9;</code>
     */
    const INT = 9;
    /**
     * Note that TEXT and VARCHAR are synonyms in Cassandra. gRPC responses will always use VARCHAR,
     * regardless of the name that was used for creation.
     *
     * Generated from protobuf enum <code>TEXT = 10 [deprecated = true];</code>
     */
    const TEXT = 10;
    /**
     * Generated from protobuf enum <code>TIMESTAMP = 11;</code>
     */
    const TIMESTAMP = 11;
    /**
     * Generated from protobuf enum <code>UUID = 12;</code>
     */
    const UUID = 12;
    /**
     * Generated from protobuf enum <code>VARCHAR = 13;</code>
     */
    const VARCHAR = 13;
    /**
     * Generated from protobuf enum <code>VARINT = 14;</code>
     */
    const VARINT = 14;
    /**
     * Generated from protobuf enum <code>TIMEUUID = 15;</code>
     */
    const TIMEUUID = 15;
    /**
     * Generated from protobuf enum <code>INET = 16;</code>
     */
    const INET = 16;
    /**
     * Generated from protobuf enum <code>DATE = 17;</code>
     */
    const DATE = 17;
    /**
     * Generated from protobuf enum <code>TIME = 18;</code>
     */
    const TIME = 18;
    /**
     * Generated from protobuf enum <code>SMALLINT = 19;</code>
     */
    const SMALLINT = 19;
    /**
     * Generated from protobuf enum <code>TINYINT = 20;</code>
     */
    const TINYINT = 20;
    /**
     * Generated from protobuf enum <code>DURATION = 21;</code>
     */
    const DURATION = 21;
    /**
     * Generated from protobuf enum <code>LINESTRING = 22;</code>
     */
    const LINESTRING = 22;
    /**
     * Generated from protobuf enum <code>POINT = 23;</code>
     */
    const POINT = 23;
    /**
     * Generated from protobuf enum <code>POLYGON = 24;</code>
     */
    const POLYGON = 24;

    private static $valueToName = [
        self::CUSTOM => 'CUSTOM',
        self::ASCII => 'ASCII',
        self::BIGINT => 'BIGINT',
        self::BLOB => 'BLOB',
        self::BOOLEAN => 'BOOLEAN',
        self::COUNTER => 'COUNTER',
        self::DECIMAL => 'DECIMAL',
        self::DOUBLE => 'DOUBLE',
        self::FLOAT => 'FLOAT',
        self::INT => 'INT',
        self::TEXT => 'TEXT',
        self::TIMESTAMP => 'TIMESTAMP',
        self::UUID => 'UUID',
        self::VARCHAR => 'VARCHAR',
        self::VARINT => 'VARINT',
        self::TIMEUUID => 'TIMEUUID',
        self::INET => 'INET',
        self::DATE => 'DATE',
        self::TIME => 'TIME',
        self::SMALLINT => 'SMALLINT',
        self::TINYINT => 'TINYINT',
        self::DURATION => 'DURATION',
        self::LINESTRING => 'LINESTRING',
        self::POINT => 'POINT',
        self::POLYGON => 'POLYGON',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

