<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query.proto

namespace Stargate\TypeSpec;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>stargate.TypeSpec.Map</code>
 */
class Map extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.stargate.TypeSpec key = 1;</code>
     */
    protected $key = null;
    /**
     * Generated from protobuf field <code>.stargate.TypeSpec value = 2;</code>
     */
    protected $value = null;
    /**
     * optional, only required on schema definition (CREATE TYPE or CREATE TABLE)
     *
     * Generated from protobuf field <code>bool frozen = 3;</code>
     */
    protected $frozen = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Stargate\TypeSpec $key
     *     @type \Stargate\TypeSpec $value
     *     @type bool $frozen
     *           optional, only required on schema definition (CREATE TYPE or CREATE TABLE)
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.stargate.TypeSpec key = 1;</code>
     * @return \Stargate\TypeSpec|null
     */
    public function getKey()
    {
        return $this->key;
    }

    public function hasKey()
    {
        return isset($this->key);
    }

    public function clearKey()
    {
        unset($this->key);
    }

    /**
     * Generated from protobuf field <code>.stargate.TypeSpec key = 1;</code>
     * @param \Stargate\TypeSpec $var
     * @return $this
     */
    public function setKey(\Stargate\TypeSpec|null $var)
    {
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.stargate.TypeSpec value = 2;</code>
     * @return \Stargate\TypeSpec|null
     */
    public function getValue()
    {
        return $this->value;
    }

    public function hasValue()
    {
        return isset($this->value);
    }

    public function clearValue()
    {
        unset($this->value);
    }

    /**
     * Generated from protobuf field <code>.stargate.TypeSpec value = 2;</code>
     * @param \Stargate\TypeSpec $var
     * @return $this
     */
    public function setValue(\Stargate\TypeSpec|null $var)
    {
        $this->value = $var;

        return $this;
    }

    /**
     * optional, only required on schema definition (CREATE TYPE or CREATE TABLE)
     *
     * Generated from protobuf field <code>bool frozen = 3;</code>
     * @return bool
     */
    public function getFrozen()
    {
        return $this->frozen;
    }

    /**
     * optional, only required on schema definition (CREATE TYPE or CREATE TABLE)
     *
     * Generated from protobuf field <code>bool frozen = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setFrozen(bool $var)
    {
        $this->frozen = $var;

        return $this;
    }

}

