<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query.proto

namespace Stargate\TypeSpec;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>stargate.TypeSpec.List</code>
 */
class PBList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.stargate.TypeSpec element = 1;</code>
     */
    protected $element = null;
    /**
     * optional, only required on schema definition (CREATE TYPE or CREATE TABLE)
     *
     * Generated from protobuf field <code>bool frozen = 2;</code>
     */
    protected $frozen = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Stargate\TypeSpec $element
     *     @type bool $frozen
     *           optional, only required on schema definition (CREATE TYPE or CREATE TABLE)
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.stargate.TypeSpec element = 1;</code>
     * @return \Stargate\TypeSpec|null
     */
    public function getElement()
    {
        return $this->element;
    }

    public function hasElement()
    {
        return isset($this->element);
    }

    public function clearElement()
    {
        unset($this->element);
    }

    /**
     * Generated from protobuf field <code>.stargate.TypeSpec element = 1;</code>
     * @param \Stargate\TypeSpec $var
     * @return $this
     */
    public function setElement(\Stargate\TypeSpec|null $var)
    {
        $this->element = $var;

        return $this;
    }

    /**
     * optional, only required on schema definition (CREATE TYPE or CREATE TABLE)
     *
     * Generated from protobuf field <code>bool frozen = 2;</code>
     * @return bool
     */
    public function getFrozen()
    {
        return $this->frozen;
    }

    /**
     * optional, only required on schema definition (CREATE TYPE or CREATE TABLE)
     *
     * Generated from protobuf field <code>bool frozen = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setFrozen(bool $var)
    {
        $this->frozen = $var;

        return $this;
    }

}

