<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query.proto

namespace Stargate\TypeSpec;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * A CQL tuple: a collection of anonymous fields.
 *
 * Generated from protobuf message <code>stargate.TypeSpec.Tuple</code>
 */
class Tuple extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .stargate.TypeSpec elements = 1;</code>
     */
    private $elements;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Stargate\TypeSpec[] $elements
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .stargate.TypeSpec elements = 1;</code>
     * @return RepeatedField<\Stargate\TypeSpec>
     */
    public function getElements()
    {
        return $this->elements;
    }

    /**
     * Generated from protobuf field <code>repeated .stargate.TypeSpec elements = 1;</code>
     * @param \Stargate\TypeSpec[] $var
     * @return $this
     */
    public function setElements(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Stargate\TypeSpec::class);
        $this->elements = $arr;

        return $this;
    }

}

