<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query.proto

namespace Stargate\TypeSpec;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * A CQL User-Defined type: a collection of named fields.
 *
 * Generated from protobuf message <code>stargate.TypeSpec.Udt</code>
 */
class Udt extends \Google\Protobuf\Internal\Message
{
    /**
     * optional, only required when returned in ResultSet or used in CREATE TYPE,
     * ignored on CREATE TABLE
     *
     * Generated from protobuf field <code>map<string, .stargate.TypeSpec> fields = 1;</code>
     */
    private $fields;
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * optional, only required on schema definition (CREATE TYPE or CREATE TABLE)
     *
     * Generated from protobuf field <code>bool frozen = 3;</code>
     */
    protected $frozen = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $fields
     *           optional, only required when returned in ResultSet or used in CREATE TYPE,
     *           ignored on CREATE TABLE
     *     @type string $name
     *     @type bool $frozen
     *           optional, only required on schema definition (CREATE TYPE or CREATE TABLE)
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * optional, only required when returned in ResultSet or used in CREATE TYPE,
     * ignored on CREATE TABLE
     *
     * Generated from protobuf field <code>map<string, .stargate.TypeSpec> fields = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getFields()
    {
        return $this->fields;
    }

    /**
     * optional, only required when returned in ResultSet or used in CREATE TYPE,
     * ignored on CREATE TABLE
     *
     * Generated from protobuf field <code>map<string, .stargate.TypeSpec> fields = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setFields(array|\Google\Protobuf\Internal\MapField $var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Stargate\TypeSpec::class);
        $this->fields = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * optional, only required on schema definition (CREATE TYPE or CREATE TABLE)
     *
     * Generated from protobuf field <code>bool frozen = 3;</code>
     * @return bool
     */
    public function getFrozen()
    {
        return $this->frozen;
    }

    /**
     * optional, only required on schema definition (CREATE TYPE or CREATE TABLE)
     *
     * Generated from protobuf field <code>bool frozen = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setFrozen(bool $var)
    {
        $this->frozen = $var;

        return $this;
    }

}

