<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query.proto

namespace Stargate;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Thrown when a query attempts to create a keyspace or table that already exists.
 *
 * Generated from protobuf message <code>stargate.AlreadyExists</code>
 */
class AlreadyExists extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string keyspace = 1;</code>
     */
    protected $keyspace = '';
    /**
     * Generated from protobuf field <code>string table = 2;</code>
     */
    protected $table = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $keyspace
     *     @type string $table
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string keyspace = 1;</code>
     * @return string
     */
    public function getKeyspace()
    {
        return $this->keyspace;
    }

    /**
     * Generated from protobuf field <code>string keyspace = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKeyspace(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->keyspace = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string table = 2;</code>
     * @return string
     */
    public function getTable()
    {
        return $this->table;
    }

    /**
     * Generated from protobuf field <code>string table = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTable(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->table = $var;

        return $this;
    }

}

