<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query.proto

namespace Stargate;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * A batch containing multiple CQL queries.
 *
 * Generated from protobuf message <code>stargate.Batch</code>
 */
class Batch extends \Google\Protobuf\Internal\Message
{
    /**
     * The type of batch.
     *
     * Generated from protobuf field <code>.stargate.Batch.Type type = 1;</code>
     */
    protected $type = 0;
    /**
     * The CQL queries with their values.
     *
     * Generated from protobuf field <code>repeated .stargate.BatchQuery queries = 2;</code>
     */
    private $queries;
    /**
     * The execution parameters for the batch.
     *
     * Generated from protobuf field <code>.stargate.BatchParameters parameters = 3;</code>
     */
    protected $parameters = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *           The type of batch.
     *     @type \Stargate\BatchQuery[] $queries
     *           The CQL queries with their values.
     *     @type \Stargate\BatchParameters $parameters
     *           The execution parameters for the batch.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * The type of batch.
     *
     * Generated from protobuf field <code>.stargate.Batch.Type type = 1;</code>
     * @return int one of the values in {@see \Stargate\Batch\Type}
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * The type of batch.
     *
     * Generated from protobuf field <code>.stargate.Batch.Type type = 1;</code>
     * @param int $var one of the values in {@see \Stargate\Batch\Type}
     * @return $this
     */
    public function setType(int $var)
    {
        GPBUtil::checkEnum($var, \Stargate\Batch\Type::class);
        $this->type = $var;

        return $this;
    }

    /**
     * The CQL queries with their values.
     *
     * Generated from protobuf field <code>repeated .stargate.BatchQuery queries = 2;</code>
     * @return RepeatedField<\Stargate\BatchQuery>
     */
    public function getQueries()
    {
        return $this->queries;
    }

    /**
     * The CQL queries with their values.
     *
     * Generated from protobuf field <code>repeated .stargate.BatchQuery queries = 2;</code>
     * @param \Stargate\BatchQuery[] $var
     * @return $this
     */
    public function setQueries(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Stargate\BatchQuery::class);
        $this->queries = $arr;

        return $this;
    }

    /**
     * The execution parameters for the batch.
     *
     * Generated from protobuf field <code>.stargate.BatchParameters parameters = 3;</code>
     * @return \Stargate\BatchParameters|null
     */
    public function getParameters()
    {
        return $this->parameters;
    }

    public function hasParameters()
    {
        return isset($this->parameters);
    }

    public function clearParameters()
    {
        unset($this->parameters);
    }

    /**
     * The execution parameters for the batch.
     *
     * Generated from protobuf field <code>.stargate.BatchParameters parameters = 3;</code>
     * @param \Stargate\BatchParameters $var
     * @return $this
     */
    public function setParameters(\Stargate\BatchParameters|null $var)
    {
        $this->parameters = $var;

        return $this;
    }

}

