<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query.proto

namespace Stargate;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * An exception occured due to a contended Compare And Set write/update.
 * The CAS operation was only partially completed and the operation may or may not get completed by
 * the contending CAS write or SERIAL/LOCAL_SERIAL read.
 *
 * Generated from protobuf message <code>stargate.CasWriteUnknown</code>
 */
class CasWriteUnknown extends \Google\Protobuf\Internal\Message
{
    /**
     * The consistency level of the operation that failed.
     *
     * Generated from protobuf field <code>.stargate.Consistency consistency = 1;</code>
     */
    protected $consistency = 0;
    /**
     * The number of replica that had acknowledged/responded to the operation before it failed.
     *
     * Generated from protobuf field <code>int32 received = 2;</code>
     */
    protected $received = 0;
    /**
     * The minimum number of replica acknowledgements/responses that were required to fulfill the
     * operation.
     *
     * Generated from protobuf field <code>int32 block_for = 3;</code>
     */
    protected $block_for = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $consistency
     *           The consistency level of the operation that failed.
     *     @type int $received
     *           The number of replica that had acknowledged/responded to the operation before it failed.
     *     @type int $block_for
     *           The minimum number of replica acknowledgements/responses that were required to fulfill the
     *           operation.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * The consistency level of the operation that failed.
     *
     * Generated from protobuf field <code>.stargate.Consistency consistency = 1;</code>
     * @return int one of the values in {@see \Stargate\Consistency}
     */
    public function getConsistency()
    {
        return $this->consistency;
    }

    /**
     * The consistency level of the operation that failed.
     *
     * Generated from protobuf field <code>.stargate.Consistency consistency = 1;</code>
     * @param int $var one of the values in {@see \Stargate\Consistency}
     * @return $this
     */
    public function setConsistency(int $var)
    {
        GPBUtil::checkEnum($var, \Stargate\Consistency::class);
        $this->consistency = $var;

        return $this;
    }

    /**
     * The number of replica that had acknowledged/responded to the operation before it failed.
     *
     * Generated from protobuf field <code>int32 received = 2;</code>
     * @return int
     */
    public function getReceived()
    {
        return $this->received;
    }

    /**
     * The number of replica that had acknowledged/responded to the operation before it failed.
     *
     * Generated from protobuf field <code>int32 received = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setReceived(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->received = $var;

        return $this;
    }

    /**
     * The minimum number of replica acknowledgements/responses that were required to fulfill the
     * operation.
     *
     * Generated from protobuf field <code>int32 block_for = 3;</code>
     * @return int
     */
    public function getBlockFor()
    {
        return $this->block_for;
    }

    /**
     * The minimum number of replica acknowledgements/responses that were required to fulfill the
     * operation.
     *
     * Generated from protobuf field <code>int32 block_for = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setBlockFor(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->block_for = $var;

        return $this;
    }

}

