<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query.proto

namespace Stargate;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * A CQL value for a collection type.
 * For lists, sets and tuples, this contains the collection elements.
 * For maps, this contains the key and values in order (e.g. key1, value1, key2, value2...)
 *
 * Generated from protobuf message <code>stargate.Collection</code>
 */
class Collection extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .stargate.Value elements = 1;</code>
     */
    private $elements;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Stargate\Value[] $elements
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .stargate.Value elements = 1;</code>
     * @return RepeatedField<\Stargate\Value>
     */
    public function getElements()
    {
        return $this->elements;
    }

    /**
     * Generated from protobuf field <code>repeated .stargate.Value elements = 1;</code>
     * @param \Stargate\Value[] $var
     * @return $this
     */
    public function setElements(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Stargate\Value::class);
        $this->elements = $arr;

        return $this;
    }

}

