<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query.proto

namespace Stargate;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Metadata about a CQL column.
 *
 * Generated from protobuf message <code>stargate.ColumnSpec</code>
 */
class ColumnSpec extends \Google\Protobuf\Internal\Message
{
    /**
     * The CQL type.
     *
     * Generated from protobuf field <code>.stargate.TypeSpec type = 1;</code>
     */
    protected $type = null;
    /**
     * The name.
     *
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Stargate\TypeSpec $type
     *           The CQL type.
     *     @type string $name
     *           The name.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * The CQL type.
     *
     * Generated from protobuf field <code>.stargate.TypeSpec type = 1;</code>
     * @return \Stargate\TypeSpec|null
     */
    public function getType()
    {
        return $this->type;
    }

    public function hasType()
    {
        return isset($this->type);
    }

    public function clearType()
    {
        unset($this->type);
    }

    /**
     * The CQL type.
     *
     * Generated from protobuf field <code>.stargate.TypeSpec type = 1;</code>
     * @param \Stargate\TypeSpec $var
     * @return $this
     */
    public function setType(\Stargate\TypeSpec|null $var)
    {
        $this->type = $var;

        return $this;
    }

    /**
     * The name.
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The name.
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

}

