<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query.proto

namespace Stargate;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * A wrapper message for Consistency, for cases where the consistency level can be unset.
 *
 * Generated from protobuf message <code>stargate.ConsistencyValue</code>
 */
class ConsistencyValue extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.stargate.Consistency value = 1;</code>
     */
    protected $value = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $value
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.stargate.Consistency value = 1;</code>
     * @return int one of the values in {@see \Stargate\Consistency}
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>.stargate.Consistency value = 1;</code>
     * @param int $var one of the values in {@see \Stargate\Consistency}
     * @return $this
     */
    public function setValue(int $var)
    {
        GPBUtil::checkEnum($var, \Stargate\Consistency::class);
        $this->value = $var;

        return $this;
    }

}

