<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query.proto

namespace Stargate;

use UnexpectedValueException;

/**
 * The consistency level used to execute a request.
 *
 * Protobuf type <code>stargate.Consistency</code>
 */
class Consistency
{
    /**
     * Generated from protobuf enum <code>ANY = 0;</code>
     */
    const ANY = 0;
    /**
     * Generated from protobuf enum <code>ONE = 1;</code>
     */
    const ONE = 1;
    /**
     * Generated from protobuf enum <code>TWO = 2;</code>
     */
    const TWO = 2;
    /**
     * Generated from protobuf enum <code>THREE = 3;</code>
     */
    const THREE = 3;
    /**
     * Generated from protobuf enum <code>QUORUM = 4;</code>
     */
    const QUORUM = 4;
    /**
     * Generated from protobuf enum <code>ALL = 5;</code>
     */
    const ALL = 5;
    /**
     * Generated from protobuf enum <code>LOCAL_QUORUM = 6;</code>
     */
    const LOCAL_QUORUM = 6;
    /**
     * Generated from protobuf enum <code>EACH_QUORUM = 7;</code>
     */
    const EACH_QUORUM = 7;
    /**
     * Generated from protobuf enum <code>SERIAL = 8;</code>
     */
    const SERIAL = 8;
    /**
     * Generated from protobuf enum <code>LOCAL_SERIAL = 9;</code>
     */
    const LOCAL_SERIAL = 9;
    /**
     * Generated from protobuf enum <code>LOCAL_ONE = 10;</code>
     */
    const LOCAL_ONE = 10;

    private static $valueToName = [
        self::ANY => 'ANY',
        self::ONE => 'ONE',
        self::TWO => 'TWO',
        self::THREE => 'THREE',
        self::QUORUM => 'QUORUM',
        self::ALL => 'ALL',
        self::LOCAL_QUORUM => 'LOCAL_QUORUM',
        self::EACH_QUORUM => 'EACH_QUORUM',
        self::SERIAL => 'SERIAL',
        self::LOCAL_SERIAL => 'LOCAL_SERIAL',
        self::LOCAL_ONE => 'LOCAL_ONE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

