<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query.proto

namespace Stargate;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>stargate.Decimal</code>
 */
class Decimal extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 scale = 1;</code>
     */
    protected $scale = 0;
    /**
     * Generated from protobuf field <code>bytes value = 3;</code>
     */
    protected $value = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $scale
     *     @type string $value
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 scale = 1;</code>
     * @return int
     */
    public function getScale()
    {
        return $this->scale;
    }

    /**
     * Generated from protobuf field <code>uint32 scale = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setScale(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->scale = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes value = 3;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>bytes value = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setValue(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->value = $var;

        return $this;
    }

}

