<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query.proto

namespace Stargate;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>stargate.Duration</code>
 */
class Duration extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>sint32 months = 1;</code>
     */
    protected $months = 0;
    /**
     * Generated from protobuf field <code>sint32 days = 2;</code>
     */
    protected $days = 0;
    /**
     * Generated from protobuf field <code>sint64 nanos = 3;</code>
     */
    protected $nanos = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $months
     *     @type int $days
     *     @type int|string $nanos
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>sint32 months = 1;</code>
     * @return int
     */
    public function getMonths()
    {
        return $this->months;
    }

    /**
     * Generated from protobuf field <code>sint32 months = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMonths(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->months = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>sint32 days = 2;</code>
     * @return int
     */
    public function getDays()
    {
        return $this->days;
    }

    /**
     * Generated from protobuf field <code>sint32 days = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setDays(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->days = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>sint64 nanos = 3;</code>
     * @return int|string
     */
    public function getNanos()
    {
        return $this->nanos;
    }

    /**
     * Generated from protobuf field <code>sint64 nanos = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNanos(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->nanos = $var;

        return $this;
    }

}

