<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query.proto

namespace Stargate;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * An error during the execution of a CQL function.
 *
 * Generated from protobuf message <code>stargate.FunctionFailure</code>
 */
class FunctionFailure extends \Google\Protobuf\Internal\Message
{
    /**
     * The keyspace containing the function.
     *
     * Generated from protobuf field <code>string keyspace = 1;</code>
     */
    protected $keyspace = '';
    /**
     * The name of the function.
     *
     * Generated from protobuf field <code>string function = 2;</code>
     */
    protected $function = '';
    /**
     * The CQL types of the arguments of the function.
     *
     * Generated from protobuf field <code>repeated string arg_types = 3;</code>
     */
    private $arg_types;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $keyspace
     *           The keyspace containing the function.
     *     @type string $function
     *           The name of the function.
     *     @type string[] $arg_types
     *           The CQL types of the arguments of the function.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * The keyspace containing the function.
     *
     * Generated from protobuf field <code>string keyspace = 1;</code>
     * @return string
     */
    public function getKeyspace()
    {
        return $this->keyspace;
    }

    /**
     * The keyspace containing the function.
     *
     * Generated from protobuf field <code>string keyspace = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKeyspace(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->keyspace = $var;

        return $this;
    }

    /**
     * The name of the function.
     *
     * Generated from protobuf field <code>string function = 2;</code>
     * @return string
     */
    public function getFunction()
    {
        return $this->function;
    }

    /**
     * The name of the function.
     *
     * Generated from protobuf field <code>string function = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFunction(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->function = $var;

        return $this;
    }

    /**
     * The CQL types of the arguments of the function.
     *
     * Generated from protobuf field <code>repeated string arg_types = 3;</code>
     * @return RepeatedField<string>
     */
    public function getArgTypes()
    {
        return $this->arg_types;
    }

    /**
     * The CQL types of the arguments of the function.
     *
     * Generated from protobuf field <code>repeated string arg_types = 3;</code>
     * @param string[] $var
     * @return $this
     */
    public function setArgTypes(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->arg_types = $arr;

        return $this;
    }

}

