<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query.proto

namespace Stargate;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * The execution parameters for a Query message.
 *
 * Generated from protobuf message <code>stargate.QueryParameters</code>
 */
class QueryParameters extends \Google\Protobuf\Internal\Message
{
    /**
     * The keyspace to use when schema element names in the query (tables, UDTs, functions) are not
     * fully qualified.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue keyspace = 1;</code>
     */
    protected $keyspace = null;
    /**
     * The consistency level.
     * If unset, it defaults to LOCAL_QUORUM.
     *
     * Generated from protobuf field <code>.stargate.ConsistencyValue consistency = 2;</code>
     */
    protected $consistency = null;
    /**
     * The maximum number of rows that will be returned in the response. If there are more results,
     * the response will contain a paging state, and additional queries will be needed to retrieve
     * subsequent pages.
     * Note that this is only a suggestion, the server reserves the right to return slightly smaller
     * or bigger pages.
     * If unset, it defaults to 100.
     *
     * Generated from protobuf field <code>.google.protobuf.Int32Value page_size = 3;</code>
     */
    protected $page_size = null;
    /**
     * A paging state that indicates where to resume iteration in the result set. This is used to
     * retrieve the next page of data when the number of results exceeds the page size.
     * This should be filled with the value returned by the previous response (see
     * ResultSet.paging_state). It is an opaque binary string that is only intended to be collected,
     * stored and reused; any attempt to modify its contents or reuse it with a different statement
     * will yield unpredictable results.
     *
     * Generated from protobuf field <code>.google.protobuf.BytesValue paging_state = 4;</code>
     */
    protected $paging_state = null;
    /**
     * Whether the server should collect tracing information about the execution of the query.
     * If this is set, then a Traces message will be included in the Response message.
     *
     * Generated from protobuf field <code>bool tracing = 5;</code>
     */
    protected $tracing = false;
    /**
     * Whether to omit ResultSet.columns in the response.
     * This can be used to optimize response size when the client already knows that information (for
     * example when fetching multiple pages for the same query).
     *
     * Generated from protobuf field <code>bool skip_metadata = 6;</code>
     */
    protected $skip_metadata = false;
    /**
     * The query timestamp (in microseconds). This is used to order mutations on the server.
     * If unset, the server will assign one based on the time it received the query.
     *
     * Generated from protobuf field <code>.google.protobuf.Int64Value timestamp = 7;</code>
     */
    protected $timestamp = null;
    /**
     * The serial consistency level (if the query is a lightweight transaction).
     * If unset, it defaults to SERIAL.
     *
     * Generated from protobuf field <code>.stargate.ConsistencyValue serial_consistency = 8;</code>
     */
    protected $serial_consistency = null;
    /**
     * Forces the current time for the query (for testing purposes).
     * This affects TTL cell liveness in read queries and local deletion time for tombstones and TTL
     * cells in update requests.
     *
     * Generated from protobuf field <code>.google.protobuf.Int32Value now_in_seconds = 9;</code>
     */
    protected $now_in_seconds = null;
    /**
     * The consistency level to use to retrieve the query trace (if tracing is set).
     * If unset, it defaults to ONE.
     *
     * Generated from protobuf field <code>.stargate.ConsistencyValue tracing_consistency = 10;</code>
     */
    protected $tracing_consistency = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\StringValue $keyspace
     *           The keyspace to use when schema element names in the query (tables, UDTs, functions) are not
     *           fully qualified.
     *     @type \Stargate\ConsistencyValue $consistency
     *           The consistency level.
     *           If unset, it defaults to LOCAL_QUORUM.
     *     @type \Google\Protobuf\Int32Value $page_size
     *           The maximum number of rows that will be returned in the response. If there are more results,
     *           the response will contain a paging state, and additional queries will be needed to retrieve
     *           subsequent pages.
     *           Note that this is only a suggestion, the server reserves the right to return slightly smaller
     *           or bigger pages.
     *           If unset, it defaults to 100.
     *     @type \Google\Protobuf\BytesValue $paging_state
     *           A paging state that indicates where to resume iteration in the result set. This is used to
     *           retrieve the next page of data when the number of results exceeds the page size.
     *           This should be filled with the value returned by the previous response (see
     *           ResultSet.paging_state). It is an opaque binary string that is only intended to be collected,
     *           stored and reused; any attempt to modify its contents or reuse it with a different statement
     *           will yield unpredictable results.
     *     @type bool $tracing
     *           Whether the server should collect tracing information about the execution of the query.
     *           If this is set, then a Traces message will be included in the Response message.
     *     @type bool $skip_metadata
     *           Whether to omit ResultSet.columns in the response.
     *           This can be used to optimize response size when the client already knows that information (for
     *           example when fetching multiple pages for the same query).
     *     @type \Google\Protobuf\Int64Value $timestamp
     *           The query timestamp (in microseconds). This is used to order mutations on the server.
     *           If unset, the server will assign one based on the time it received the query.
     *     @type \Stargate\ConsistencyValue $serial_consistency
     *           The serial consistency level (if the query is a lightweight transaction).
     *           If unset, it defaults to SERIAL.
     *     @type \Google\Protobuf\Int32Value $now_in_seconds
     *           Forces the current time for the query (for testing purposes).
     *           This affects TTL cell liveness in read queries and local deletion time for tombstones and TTL
     *           cells in update requests.
     *     @type \Stargate\ConsistencyValue $tracing_consistency
     *           The consistency level to use to retrieve the query trace (if tracing is set).
     *           If unset, it defaults to ONE.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * The keyspace to use when schema element names in the query (tables, UDTs, functions) are not
     * fully qualified.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue keyspace = 1;</code>
     * @return \Google\Protobuf\StringValue|null
     */
    public function getKeyspace()
    {
        return $this->keyspace;
    }

    public function hasKeyspace()
    {
        return isset($this->keyspace);
    }

    public function clearKeyspace()
    {
        unset($this->keyspace);
    }

    /**
     * Returns the unboxed value from <code>getKeyspace()</code>

     * The keyspace to use when schema element names in the query (tables, UDTs, functions) are not
     * fully qualified.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue keyspace = 1;</code>
     * @return string|null
     */
    public function getKeyspaceUnwrapped()
    {
        return $this->readWrapperValue("keyspace");
    }

    /**
     * The keyspace to use when schema element names in the query (tables, UDTs, functions) are not
     * fully qualified.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue keyspace = 1;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setKeyspace(\Google\Protobuf\StringValue|null $var)
    {
        $this->keyspace = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\StringValue object.

     * The keyspace to use when schema element names in the query (tables, UDTs, functions) are not
     * fully qualified.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue keyspace = 1;</code>
     * @param string|null $var
     * @return $this
     */
    public function setKeyspaceUnwrapped($var)
    {
        $this->writeWrapperValue("keyspace", $var);
        return $this;}

    /**
     * The consistency level.
     * If unset, it defaults to LOCAL_QUORUM.
     *
     * Generated from protobuf field <code>.stargate.ConsistencyValue consistency = 2;</code>
     * @return \Stargate\ConsistencyValue|null
     */
    public function getConsistency()
    {
        return $this->consistency;
    }

    public function hasConsistency()
    {
        return isset($this->consistency);
    }

    public function clearConsistency()
    {
        unset($this->consistency);
    }

    /**
     * The consistency level.
     * If unset, it defaults to LOCAL_QUORUM.
     *
     * Generated from protobuf field <code>.stargate.ConsistencyValue consistency = 2;</code>
     * @param \Stargate\ConsistencyValue $var
     * @return $this
     */
    public function setConsistency(\Stargate\ConsistencyValue|null $var)
    {
        $this->consistency = $var;

        return $this;
    }

    /**
     * The maximum number of rows that will be returned in the response. If there are more results,
     * the response will contain a paging state, and additional queries will be needed to retrieve
     * subsequent pages.
     * Note that this is only a suggestion, the server reserves the right to return slightly smaller
     * or bigger pages.
     * If unset, it defaults to 100.
     *
     * Generated from protobuf field <code>.google.protobuf.Int32Value page_size = 3;</code>
     * @return \Google\Protobuf\Int32Value|null
     */
    public function getPageSize()
    {
        return $this->page_size;
    }

    public function hasPageSize()
    {
        return isset($this->page_size);
    }

    public function clearPageSize()
    {
        unset($this->page_size);
    }

    /**
     * Returns the unboxed value from <code>getPageSize()</code>

     * The maximum number of rows that will be returned in the response. If there are more results,
     * the response will contain a paging state, and additional queries will be needed to retrieve
     * subsequent pages.
     * Note that this is only a suggestion, the server reserves the right to return slightly smaller
     * or bigger pages.
     * If unset, it defaults to 100.
     *
     * Generated from protobuf field <code>.google.protobuf.Int32Value page_size = 3;</code>
     * @return int|null
     */
    public function getPageSizeUnwrapped()
    {
        return $this->readWrapperValue("page_size");
    }

    /**
     * The maximum number of rows that will be returned in the response. If there are more results,
     * the response will contain a paging state, and additional queries will be needed to retrieve
     * subsequent pages.
     * Note that this is only a suggestion, the server reserves the right to return slightly smaller
     * or bigger pages.
     * If unset, it defaults to 100.
     *
     * Generated from protobuf field <code>.google.protobuf.Int32Value page_size = 3;</code>
     * @param \Google\Protobuf\Int32Value $var
     * @return $this
     */
    public function setPageSize(\Google\Protobuf\Int32Value|null $var)
    {
        $this->page_size = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\Int32Value object.

     * The maximum number of rows that will be returned in the response. If there are more results,
     * the response will contain a paging state, and additional queries will be needed to retrieve
     * subsequent pages.
     * Note that this is only a suggestion, the server reserves the right to return slightly smaller
     * or bigger pages.
     * If unset, it defaults to 100.
     *
     * Generated from protobuf field <code>.google.protobuf.Int32Value page_size = 3;</code>
     * @param int|null $var
     * @return $this
     */
    public function setPageSizeUnwrapped($var)
    {
        $this->writeWrapperValue("page_size", $var);
        return $this;}

    /**
     * A paging state that indicates where to resume iteration in the result set. This is used to
     * retrieve the next page of data when the number of results exceeds the page size.
     * This should be filled with the value returned by the previous response (see
     * ResultSet.paging_state). It is an opaque binary string that is only intended to be collected,
     * stored and reused; any attempt to modify its contents or reuse it with a different statement
     * will yield unpredictable results.
     *
     * Generated from protobuf field <code>.google.protobuf.BytesValue paging_state = 4;</code>
     * @return \Google\Protobuf\BytesValue|null
     */
    public function getPagingState()
    {
        return $this->paging_state;
    }

    public function hasPagingState()
    {
        return isset($this->paging_state);
    }

    public function clearPagingState()
    {
        unset($this->paging_state);
    }

    /**
     * Returns the unboxed value from <code>getPagingState()</code>

     * A paging state that indicates where to resume iteration in the result set. This is used to
     * retrieve the next page of data when the number of results exceeds the page size.
     * This should be filled with the value returned by the previous response (see
     * ResultSet.paging_state). It is an opaque binary string that is only intended to be collected,
     * stored and reused; any attempt to modify its contents or reuse it with a different statement
     * will yield unpredictable results.
     *
     * Generated from protobuf field <code>.google.protobuf.BytesValue paging_state = 4;</code>
     * @return string|null
     */
    public function getPagingStateUnwrapped()
    {
        return $this->readWrapperValue("paging_state");
    }

    /**
     * A paging state that indicates where to resume iteration in the result set. This is used to
     * retrieve the next page of data when the number of results exceeds the page size.
     * This should be filled with the value returned by the previous response (see
     * ResultSet.paging_state). It is an opaque binary string that is only intended to be collected,
     * stored and reused; any attempt to modify its contents or reuse it with a different statement
     * will yield unpredictable results.
     *
     * Generated from protobuf field <code>.google.protobuf.BytesValue paging_state = 4;</code>
     * @param \Google\Protobuf\BytesValue $var
     * @return $this
     */
    public function setPagingState(\Google\Protobuf\BytesValue|null $var)
    {
        $this->paging_state = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\BytesValue object.

     * A paging state that indicates where to resume iteration in the result set. This is used to
     * retrieve the next page of data when the number of results exceeds the page size.
     * This should be filled with the value returned by the previous response (see
     * ResultSet.paging_state). It is an opaque binary string that is only intended to be collected,
     * stored and reused; any attempt to modify its contents or reuse it with a different statement
     * will yield unpredictable results.
     *
     * Generated from protobuf field <code>.google.protobuf.BytesValue paging_state = 4;</code>
     * @param string|null $var
     * @return $this
     */
    public function setPagingStateUnwrapped($var)
    {
        $this->writeWrapperValue("paging_state", $var);
        return $this;}

    /**
     * Whether the server should collect tracing information about the execution of the query.
     * If this is set, then a Traces message will be included in the Response message.
     *
     * Generated from protobuf field <code>bool tracing = 5;</code>
     * @return bool
     */
    public function getTracing()
    {
        return $this->tracing;
    }

    /**
     * Whether the server should collect tracing information about the execution of the query.
     * If this is set, then a Traces message will be included in the Response message.
     *
     * Generated from protobuf field <code>bool tracing = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setTracing(bool $var)
    {
        $this->tracing = $var;

        return $this;
    }

    /**
     * Whether to omit ResultSet.columns in the response.
     * This can be used to optimize response size when the client already knows that information (for
     * example when fetching multiple pages for the same query).
     *
     * Generated from protobuf field <code>bool skip_metadata = 6;</code>
     * @return bool
     */
    public function getSkipMetadata()
    {
        return $this->skip_metadata;
    }

    /**
     * Whether to omit ResultSet.columns in the response.
     * This can be used to optimize response size when the client already knows that information (for
     * example when fetching multiple pages for the same query).
     *
     * Generated from protobuf field <code>bool skip_metadata = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setSkipMetadata(bool $var)
    {
        $this->skip_metadata = $var;

        return $this;
    }

    /**
     * The query timestamp (in microseconds). This is used to order mutations on the server.
     * If unset, the server will assign one based on the time it received the query.
     *
     * Generated from protobuf field <code>.google.protobuf.Int64Value timestamp = 7;</code>
     * @return \Google\Protobuf\Int64Value|null
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    public function hasTimestamp()
    {
        return isset($this->timestamp);
    }

    public function clearTimestamp()
    {
        unset($this->timestamp);
    }

    /**
     * Returns the unboxed value from <code>getTimestamp()</code>

     * The query timestamp (in microseconds). This is used to order mutations on the server.
     * If unset, the server will assign one based on the time it received the query.
     *
     * Generated from protobuf field <code>.google.protobuf.Int64Value timestamp = 7;</code>
     * @return int|string|null
     */
    public function getTimestampUnwrapped()
    {
        return $this->readWrapperValue("timestamp");
    }

    /**
     * The query timestamp (in microseconds). This is used to order mutations on the server.
     * If unset, the server will assign one based on the time it received the query.
     *
     * Generated from protobuf field <code>.google.protobuf.Int64Value timestamp = 7;</code>
     * @param \Google\Protobuf\Int64Value $var
     * @return $this
     */
    public function setTimestamp(\Google\Protobuf\Int64Value|null $var)
    {
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\Int64Value object.

     * The query timestamp (in microseconds). This is used to order mutations on the server.
     * If unset, the server will assign one based on the time it received the query.
     *
     * Generated from protobuf field <code>.google.protobuf.Int64Value timestamp = 7;</code>
     * @param int|string|null $var
     * @return $this
     */
    public function setTimestampUnwrapped($var)
    {
        $this->writeWrapperValue("timestamp", $var);
        return $this;}

    /**
     * The serial consistency level (if the query is a lightweight transaction).
     * If unset, it defaults to SERIAL.
     *
     * Generated from protobuf field <code>.stargate.ConsistencyValue serial_consistency = 8;</code>
     * @return \Stargate\ConsistencyValue|null
     */
    public function getSerialConsistency()
    {
        return $this->serial_consistency;
    }

    public function hasSerialConsistency()
    {
        return isset($this->serial_consistency);
    }

    public function clearSerialConsistency()
    {
        unset($this->serial_consistency);
    }

    /**
     * The serial consistency level (if the query is a lightweight transaction).
     * If unset, it defaults to SERIAL.
     *
     * Generated from protobuf field <code>.stargate.ConsistencyValue serial_consistency = 8;</code>
     * @param \Stargate\ConsistencyValue $var
     * @return $this
     */
    public function setSerialConsistency(\Stargate\ConsistencyValue|null $var)
    {
        $this->serial_consistency = $var;

        return $this;
    }

    /**
     * Forces the current time for the query (for testing purposes).
     * This affects TTL cell liveness in read queries and local deletion time for tombstones and TTL
     * cells in update requests.
     *
     * Generated from protobuf field <code>.google.protobuf.Int32Value now_in_seconds = 9;</code>
     * @return \Google\Protobuf\Int32Value|null
     */
    public function getNowInSeconds()
    {
        return $this->now_in_seconds;
    }

    public function hasNowInSeconds()
    {
        return isset($this->now_in_seconds);
    }

    public function clearNowInSeconds()
    {
        unset($this->now_in_seconds);
    }

    /**
     * Returns the unboxed value from <code>getNowInSeconds()</code>

     * Forces the current time for the query (for testing purposes).
     * This affects TTL cell liveness in read queries and local deletion time for tombstones and TTL
     * cells in update requests.
     *
     * Generated from protobuf field <code>.google.protobuf.Int32Value now_in_seconds = 9;</code>
     * @return int|null
     */
    public function getNowInSecondsUnwrapped()
    {
        return $this->readWrapperValue("now_in_seconds");
    }

    /**
     * Forces the current time for the query (for testing purposes).
     * This affects TTL cell liveness in read queries and local deletion time for tombstones and TTL
     * cells in update requests.
     *
     * Generated from protobuf field <code>.google.protobuf.Int32Value now_in_seconds = 9;</code>
     * @param \Google\Protobuf\Int32Value $var
     * @return $this
     */
    public function setNowInSeconds(\Google\Protobuf\Int32Value|null $var)
    {
        $this->now_in_seconds = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\Int32Value object.

     * Forces the current time for the query (for testing purposes).
     * This affects TTL cell liveness in read queries and local deletion time for tombstones and TTL
     * cells in update requests.
     *
     * Generated from protobuf field <code>.google.protobuf.Int32Value now_in_seconds = 9;</code>
     * @param int|null $var
     * @return $this
     */
    public function setNowInSecondsUnwrapped($var)
    {
        $this->writeWrapperValue("now_in_seconds", $var);
        return $this;}

    /**
     * The consistency level to use to retrieve the query trace (if tracing is set).
     * If unset, it defaults to ONE.
     *
     * Generated from protobuf field <code>.stargate.ConsistencyValue tracing_consistency = 10;</code>
     * @return \Stargate\ConsistencyValue|null
     */
    public function getTracingConsistency()
    {
        return $this->tracing_consistency;
    }

    public function hasTracingConsistency()
    {
        return isset($this->tracing_consistency);
    }

    public function clearTracingConsistency()
    {
        unset($this->tracing_consistency);
    }

    /**
     * The consistency level to use to retrieve the query trace (if tracing is set).
     * If unset, it defaults to ONE.
     *
     * Generated from protobuf field <code>.stargate.ConsistencyValue tracing_consistency = 10;</code>
     * @param \Stargate\ConsistencyValue $var
     * @return $this
     */
    public function setTracingConsistency(\Stargate\ConsistencyValue|null $var)
    {
        $this->tracing_consistency = $var;

        return $this;
    }

}

