<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query.proto

namespace Stargate;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * A single CQL query.
 *
 * Generated from protobuf message <code>stargate.Query</code>
 */
class Query extends \Google\Protobuf\Internal\Message
{
    /**
     * The query string. It can contain anonymous placeholders identified by a question mark (?), or
     * named placeholders prefixed by a column (:name).
     *
     * Generated from protobuf field <code>string cql = 1;</code>
     */
    protected $cql = '';
    /**
     * The values to fill the placeholders in the query string.
     *
     * Generated from protobuf field <code>.stargate.Values values = 2;</code>
     */
    protected $values = null;
    /**
     * The execution parameters for the query.
     *
     * Generated from protobuf field <code>.stargate.QueryParameters parameters = 3;</code>
     */
    protected $parameters = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $cql
     *           The query string. It can contain anonymous placeholders identified by a question mark (?), or
     *           named placeholders prefixed by a column (:name).
     *     @type \Stargate\Values $values
     *           The values to fill the placeholders in the query string.
     *     @type \Stargate\QueryParameters $parameters
     *           The execution parameters for the query.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * The query string. It can contain anonymous placeholders identified by a question mark (?), or
     * named placeholders prefixed by a column (:name).
     *
     * Generated from protobuf field <code>string cql = 1;</code>
     * @return string
     */
    public function getCql()
    {
        return $this->cql;
    }

    /**
     * The query string. It can contain anonymous placeholders identified by a question mark (?), or
     * named placeholders prefixed by a column (:name).
     *
     * Generated from protobuf field <code>string cql = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCql(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->cql = $var;

        return $this;
    }

    /**
     * The values to fill the placeholders in the query string.
     *
     * Generated from protobuf field <code>.stargate.Values values = 2;</code>
     * @return \Stargate\Values|null
     */
    public function getValues()
    {
        return $this->values;
    }

    public function hasValues()
    {
        return isset($this->values);
    }

    public function clearValues()
    {
        unset($this->values);
    }

    /**
     * The values to fill the placeholders in the query string.
     *
     * Generated from protobuf field <code>.stargate.Values values = 2;</code>
     * @param \Stargate\Values $var
     * @return $this
     */
    public function setValues(\Stargate\Values|null $var)
    {
        $this->values = $var;

        return $this;
    }

    /**
     * The execution parameters for the query.
     *
     * Generated from protobuf field <code>.stargate.QueryParameters parameters = 3;</code>
     * @return \Stargate\QueryParameters|null
     */
    public function getParameters()
    {
        return $this->parameters;
    }

    public function hasParameters()
    {
        return isset($this->parameters);
    }

    public function clearParameters()
    {
        unset($this->parameters);
    }

    /**
     * The execution parameters for the query.
     *
     * Generated from protobuf field <code>.stargate.QueryParameters parameters = 3;</code>
     * @param \Stargate\QueryParameters $var
     * @return $this
     */
    public function setParameters(\Stargate\QueryParameters|null $var)
    {
        $this->parameters = $var;

        return $this;
    }

}

