<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query.proto

namespace Stargate;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * A non-timeout error during a read query.
 * This happens when some of the replicas that were contacted by the coordinator replied with an
 * error.
 *
 * Generated from protobuf message <code>stargate.ReadFailure</code>
 */
class ReadFailure extends \Google\Protobuf\Internal\Message
{
    /**
     * The consistency level of the operation that failed.
     *
     * Generated from protobuf field <code>.stargate.Consistency consistency = 1;</code>
     */
    protected $consistency = 0;
    /**
     * The number of replica that had acknowledged/responded to the operation before it failed.
     *
     * Generated from protobuf field <code>int32 received = 2;</code>
     */
    protected $received = 0;
    /**
     * The minimum number of replica acknowledgements/responses that were required to fulfill the
     * operation.
     *
     * Generated from protobuf field <code>int32 block_for = 3;</code>
     */
    protected $block_for = 0;
    /**
     * The number of replicas that experienced a failure while executing the request.
     *
     * Generated from protobuf field <code>int32 num_failures = 4;</code>
     */
    protected $num_failures = 0;
    /**
     * Whether the actual data was amongst the received replica responses.
     * During reads, Cassandra doesn't request data from every replica to minimize internal network
     * traffic. Instead, some replicas are only asked for a checksum of the data. A read timeout may
     * occur even if enough replicas have responded to fulfill the consistency level, if only checksum
     * responses have been received. This field allows to detect that case.
     *
     * Generated from protobuf field <code>bool data_present = 5;</code>
     */
    protected $data_present = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $consistency
     *           The consistency level of the operation that failed.
     *     @type int $received
     *           The number of replica that had acknowledged/responded to the operation before it failed.
     *     @type int $block_for
     *           The minimum number of replica acknowledgements/responses that were required to fulfill the
     *           operation.
     *     @type int $num_failures
     *           The number of replicas that experienced a failure while executing the request.
     *     @type bool $data_present
     *           Whether the actual data was amongst the received replica responses.
     *           During reads, Cassandra doesn't request data from every replica to minimize internal network
     *           traffic. Instead, some replicas are only asked for a checksum of the data. A read timeout may
     *           occur even if enough replicas have responded to fulfill the consistency level, if only checksum
     *           responses have been received. This field allows to detect that case.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * The consistency level of the operation that failed.
     *
     * Generated from protobuf field <code>.stargate.Consistency consistency = 1;</code>
     * @return int one of the values in {@see \Stargate\Consistency}
     */
    public function getConsistency()
    {
        return $this->consistency;
    }

    /**
     * The consistency level of the operation that failed.
     *
     * Generated from protobuf field <code>.stargate.Consistency consistency = 1;</code>
     * @param int $var one of the values in {@see \Stargate\Consistency}
     * @return $this
     */
    public function setConsistency(int $var)
    {
        GPBUtil::checkEnum($var, \Stargate\Consistency::class);
        $this->consistency = $var;

        return $this;
    }

    /**
     * The number of replica that had acknowledged/responded to the operation before it failed.
     *
     * Generated from protobuf field <code>int32 received = 2;</code>
     * @return int
     */
    public function getReceived()
    {
        return $this->received;
    }

    /**
     * The number of replica that had acknowledged/responded to the operation before it failed.
     *
     * Generated from protobuf field <code>int32 received = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setReceived(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->received = $var;

        return $this;
    }

    /**
     * The minimum number of replica acknowledgements/responses that were required to fulfill the
     * operation.
     *
     * Generated from protobuf field <code>int32 block_for = 3;</code>
     * @return int
     */
    public function getBlockFor()
    {
        return $this->block_for;
    }

    /**
     * The minimum number of replica acknowledgements/responses that were required to fulfill the
     * operation.
     *
     * Generated from protobuf field <code>int32 block_for = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setBlockFor(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->block_for = $var;

        return $this;
    }

    /**
     * The number of replicas that experienced a failure while executing the request.
     *
     * Generated from protobuf field <code>int32 num_failures = 4;</code>
     * @return int
     */
    public function getNumFailures()
    {
        return $this->num_failures;
    }

    /**
     * The number of replicas that experienced a failure while executing the request.
     *
     * Generated from protobuf field <code>int32 num_failures = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setNumFailures(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->num_failures = $var;

        return $this;
    }

    /**
     * Whether the actual data was amongst the received replica responses.
     * During reads, Cassandra doesn't request data from every replica to minimize internal network
     * traffic. Instead, some replicas are only asked for a checksum of the data. A read timeout may
     * occur even if enough replicas have responded to fulfill the consistency level, if only checksum
     * responses have been received. This field allows to detect that case.
     *
     * Generated from protobuf field <code>bool data_present = 5;</code>
     * @return bool
     */
    public function getDataPresent()
    {
        return $this->data_present;
    }

    /**
     * Whether the actual data was amongst the received replica responses.
     * During reads, Cassandra doesn't request data from every replica to minimize internal network
     * traffic. Instead, some replicas are only asked for a checksum of the data. A read timeout may
     * occur even if enough replicas have responded to fulfill the consistency level, if only checksum
     * responses have been received. This field allows to detect that case.
     *
     * Generated from protobuf field <code>bool data_present = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setDataPresent(bool $var)
    {
        $this->data_present = $var;

        return $this;
    }

}

