<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query.proto

namespace Stargate;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * The response to a Query or Batch message.
 *
 * Generated from protobuf message <code>stargate.Response</code>
 */
class Response extends \Google\Protobuf\Internal\Message
{
    /**
     * The server-side warnings for the query, if any.
     *
     * Generated from protobuf field <code>repeated string warnings = 2;</code>
     */
    private $warnings;
    /**
     * The tracing information, if it was requested for the query.
     *
     * Generated from protobuf field <code>.stargate.Traces traces = 3;</code>
     */
    protected $traces = null;
    protected $result;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Stargate\ResultSet $result_set
     *           The result data.
     *     @type \Stargate\SchemaChange $schema_change
     *           How the query changed the CQL schema.
     *     @type string[] $warnings
     *           The server-side warnings for the query, if any.
     *     @type \Stargate\Traces $traces
     *           The tracing information, if it was requested for the query.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * The result data.
     *
     * Generated from protobuf field <code>.stargate.ResultSet result_set = 1;</code>
     * @return \Stargate\ResultSet|null
     */
    public function getResultSet()
    {
        return $this->readOneof(1);
    }

    public function hasResultSet()
    {
        return $this->hasOneof(1);
    }

    /**
     * The result data.
     *
     * Generated from protobuf field <code>.stargate.ResultSet result_set = 1;</code>
     * @param \Stargate\ResultSet $var
     * @return $this
     */
    public function setResultSet(\Stargate\ResultSet|null $var)
    {
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * How the query changed the CQL schema.
     *
     * Generated from protobuf field <code>.stargate.SchemaChange schema_change = 4;</code>
     * @return \Stargate\SchemaChange|null
     */
    public function getSchemaChange()
    {
        return $this->readOneof(4);
    }

    public function hasSchemaChange()
    {
        return $this->hasOneof(4);
    }

    /**
     * How the query changed the CQL schema.
     *
     * Generated from protobuf field <code>.stargate.SchemaChange schema_change = 4;</code>
     * @param \Stargate\SchemaChange $var
     * @return $this
     */
    public function setSchemaChange(\Stargate\SchemaChange|null $var)
    {
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * The server-side warnings for the query, if any.
     *
     * Generated from protobuf field <code>repeated string warnings = 2;</code>
     * @return RepeatedField<string>
     */
    public function getWarnings()
    {
        return $this->warnings;
    }

    /**
     * The server-side warnings for the query, if any.
     *
     * Generated from protobuf field <code>repeated string warnings = 2;</code>
     * @param string[] $var
     * @return $this
     */
    public function setWarnings(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->warnings = $arr;

        return $this;
    }

    /**
     * The tracing information, if it was requested for the query.
     *
     * Generated from protobuf field <code>.stargate.Traces traces = 3;</code>
     * @return \Stargate\Traces|null
     */
    public function getTraces()
    {
        return $this->traces;
    }

    public function hasTraces()
    {
        return isset($this->traces);
    }

    public function clearTraces()
    {
        unset($this->traces);
    }

    /**
     * The tracing information, if it was requested for the query.
     *
     * Generated from protobuf field <code>.stargate.Traces traces = 3;</code>
     * @param \Stargate\Traces $var
     * @return $this
     */
    public function setTraces(\Stargate\Traces|null $var)
    {
        $this->traces = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getResult()
    {
        return $this->whichOneof("result");
    }

}

