<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query.proto

namespace Stargate;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * The data returned in response to a CQL query.
 *
 * Generated from protobuf message <code>stargate.ResultSet</code>
 */
class ResultSet extends \Google\Protobuf\Internal\Message
{
    /**
     * Metadata about the columns that this result set contains.
     * This may be omitted if explicitly requested by the client (see QueryParameters.skip_metadata
     * and BatchParameters.skip_metadata).
     *
     * Generated from protobuf field <code>repeated .stargate.ColumnSpec columns = 1;</code>
     */
    private $columns;
    /**
     * The rows of CQL data.
     *
     * Generated from protobuf field <code>repeated .stargate.Row rows = 2;</code>
     */
    private $rows;
    /**
     * If there are more pages, a paging state that will allow the client to build a new query for the
     * next page.
     *
     * Generated from protobuf field <code>.google.protobuf.BytesValue paging_state = 3;</code>
     */
    protected $paging_state = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Stargate\ColumnSpec[] $columns
     *           Metadata about the columns that this result set contains.
     *           This may be omitted if explicitly requested by the client (see QueryParameters.skip_metadata
     *           and BatchParameters.skip_metadata).
     *     @type \Stargate\Row[] $rows
     *           The rows of CQL data.
     *     @type \Google\Protobuf\BytesValue $paging_state
     *           If there are more pages, a paging state that will allow the client to build a new query for the
     *           next page.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * Metadata about the columns that this result set contains.
     * This may be omitted if explicitly requested by the client (see QueryParameters.skip_metadata
     * and BatchParameters.skip_metadata).
     *
     * Generated from protobuf field <code>repeated .stargate.ColumnSpec columns = 1;</code>
     * @return RepeatedField<\Stargate\ColumnSpec>
     */
    public function getColumns()
    {
        return $this->columns;
    }

    /**
     * Metadata about the columns that this result set contains.
     * This may be omitted if explicitly requested by the client (see QueryParameters.skip_metadata
     * and BatchParameters.skip_metadata).
     *
     * Generated from protobuf field <code>repeated .stargate.ColumnSpec columns = 1;</code>
     * @param \Stargate\ColumnSpec[] $var
     * @return $this
     */
    public function setColumns(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Stargate\ColumnSpec::class);
        $this->columns = $arr;

        return $this;
    }

    /**
     * The rows of CQL data.
     *
     * Generated from protobuf field <code>repeated .stargate.Row rows = 2;</code>
     * @return RepeatedField<\Stargate\Row>
     */
    public function getRows()
    {
        return $this->rows;
    }

    /**
     * The rows of CQL data.
     *
     * Generated from protobuf field <code>repeated .stargate.Row rows = 2;</code>
     * @param \Stargate\Row[] $var
     * @return $this
     */
    public function setRows(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Stargate\Row::class);
        $this->rows = $arr;

        return $this;
    }

    /**
     * If there are more pages, a paging state that will allow the client to build a new query for the
     * next page.
     *
     * Generated from protobuf field <code>.google.protobuf.BytesValue paging_state = 3;</code>
     * @return \Google\Protobuf\BytesValue|null
     */
    public function getPagingState()
    {
        return $this->paging_state;
    }

    public function hasPagingState()
    {
        return isset($this->paging_state);
    }

    public function clearPagingState()
    {
        unset($this->paging_state);
    }

    /**
     * Returns the unboxed value from <code>getPagingState()</code>

     * If there are more pages, a paging state that will allow the client to build a new query for the
     * next page.
     *
     * Generated from protobuf field <code>.google.protobuf.BytesValue paging_state = 3;</code>
     * @return string|null
     */
    public function getPagingStateUnwrapped()
    {
        return $this->readWrapperValue("paging_state");
    }

    /**
     * If there are more pages, a paging state that will allow the client to build a new query for the
     * next page.
     *
     * Generated from protobuf field <code>.google.protobuf.BytesValue paging_state = 3;</code>
     * @param \Google\Protobuf\BytesValue $var
     * @return $this
     */
    public function setPagingState(\Google\Protobuf\BytesValue|null $var)
    {
        $this->paging_state = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\BytesValue object.

     * If there are more pages, a paging state that will allow the client to build a new query for the
     * next page.
     *
     * Generated from protobuf field <code>.google.protobuf.BytesValue paging_state = 3;</code>
     * @param string|null $var
     * @return $this
     */
    public function setPagingStateUnwrapped($var)
    {
        $this->writeWrapperValue("paging_state", $var);
        return $this;}

}

