<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query.proto

namespace Stargate;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * A single row in a result set.
 *
 * Generated from protobuf message <code>stargate.Row</code>
 */
class Row extends \Google\Protobuf\Internal\Message
{
    /**
     * The values for the columns (in the same order as ResultSet.columns).
     *
     * Generated from protobuf field <code>repeated .stargate.Value values = 1;</code>
     */
    private $values;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Stargate\Value[] $values
     *           The values for the columns (in the same order as ResultSet.columns).
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * The values for the columns (in the same order as ResultSet.columns).
     *
     * Generated from protobuf field <code>repeated .stargate.Value values = 1;</code>
     * @return RepeatedField<\Stargate\Value>
     */
    public function getValues()
    {
        return $this->values;
    }

    /**
     * The values for the columns (in the same order as ResultSet.columns).
     *
     * Generated from protobuf field <code>repeated .stargate.Value values = 1;</code>
     * @param \Stargate\Value[] $var
     * @return $this
     */
    public function setValues(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Stargate\Value::class);
        $this->values = $arr;

        return $this;
    }

}

