<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query.proto

namespace Stargate;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * TODO: does this need to include indexes and materialized views?
 * If a Query message is a DDL statement, this will be included in the Response to describe the
 * how the CQL schema was impacted.
 *
 * Generated from protobuf message <code>stargate.SchemaChange</code>
 */
class SchemaChange extends \Google\Protobuf\Internal\Message
{
    /**
     * The nature of the change (created, updated or dropped).
     *
     * Generated from protobuf field <code>.stargate.SchemaChange.Type change_type = 1;</code>
     */
    protected $change_type = 0;
    /**
     * The type of schema object that was affected.
     *
     * Generated from protobuf field <code>.stargate.SchemaChange.Target target = 2;</code>
     */
    protected $target = 0;
    /**
     * The name of the keyspace.
     *
     * Generated from protobuf field <code>string keyspace = 3;</code>
     */
    protected $keyspace = '';
    /**
     * If the target is a keyspace element (table, type, etc), its name.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue name = 4;</code>
     */
    protected $name = null;
    /**
     * If the target is a function or aggregate, the CQL types of the arguments.
     *
     * Generated from protobuf field <code>repeated string argument_types = 5;</code>
     */
    private $argument_types;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $change_type
     *           The nature of the change (created, updated or dropped).
     *     @type int $target
     *           The type of schema object that was affected.
     *     @type string $keyspace
     *           The name of the keyspace.
     *     @type \Google\Protobuf\StringValue $name
     *           If the target is a keyspace element (table, type, etc), its name.
     *     @type string[] $argument_types
     *           If the target is a function or aggregate, the CQL types of the arguments.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * The nature of the change (created, updated or dropped).
     *
     * Generated from protobuf field <code>.stargate.SchemaChange.Type change_type = 1;</code>
     * @return int one of the values in {@see \Stargate\SchemaChange\Type}
     */
    public function getChangeType()
    {
        return $this->change_type;
    }

    /**
     * The nature of the change (created, updated or dropped).
     *
     * Generated from protobuf field <code>.stargate.SchemaChange.Type change_type = 1;</code>
     * @param int $var one of the values in {@see \Stargate\SchemaChange\Type}
     * @return $this
     */
    public function setChangeType(int $var)
    {
        GPBUtil::checkEnum($var, \Stargate\SchemaChange\Type::class);
        $this->change_type = $var;

        return $this;
    }

    /**
     * The type of schema object that was affected.
     *
     * Generated from protobuf field <code>.stargate.SchemaChange.Target target = 2;</code>
     * @return int one of the values in {@see \Stargate\SchemaChange\Target}
     */
    public function getTarget()
    {
        return $this->target;
    }

    /**
     * The type of schema object that was affected.
     *
     * Generated from protobuf field <code>.stargate.SchemaChange.Target target = 2;</code>
     * @param int $var one of the values in {@see \Stargate\SchemaChange\Target}
     * @return $this
     */
    public function setTarget(int $var)
    {
        GPBUtil::checkEnum($var, \Stargate\SchemaChange\Target::class);
        $this->target = $var;

        return $this;
    }

    /**
     * The name of the keyspace.
     *
     * Generated from protobuf field <code>string keyspace = 3;</code>
     * @return string
     */
    public function getKeyspace()
    {
        return $this->keyspace;
    }

    /**
     * The name of the keyspace.
     *
     * Generated from protobuf field <code>string keyspace = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setKeyspace(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->keyspace = $var;

        return $this;
    }

    /**
     * If the target is a keyspace element (table, type, etc), its name.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue name = 4;</code>
     * @return \Google\Protobuf\StringValue|null
     */
    public function getName()
    {
        return $this->name;
    }

    public function hasName()
    {
        return isset($this->name);
    }

    public function clearName()
    {
        unset($this->name);
    }

    /**
     * Returns the unboxed value from <code>getName()</code>

     * If the target is a keyspace element (table, type, etc), its name.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue name = 4;</code>
     * @return string|null
     */
    public function getNameUnwrapped()
    {
        return $this->readWrapperValue("name");
    }

    /**
     * If the target is a keyspace element (table, type, etc), its name.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue name = 4;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setName(\Google\Protobuf\StringValue|null $var)
    {
        $this->name = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\StringValue object.

     * If the target is a keyspace element (table, type, etc), its name.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue name = 4;</code>
     * @param string|null $var
     * @return $this
     */
    public function setNameUnwrapped($var)
    {
        $this->writeWrapperValue("name", $var);
        return $this;}

    /**
     * If the target is a function or aggregate, the CQL types of the arguments.
     *
     * Generated from protobuf field <code>repeated string argument_types = 5;</code>
     * @return RepeatedField<string>
     */
    public function getArgumentTypes()
    {
        return $this->argument_types;
    }

    /**
     * If the target is a function or aggregate, the CQL types of the arguments.
     *
     * Generated from protobuf field <code>repeated string argument_types = 5;</code>
     * @param string[] $var
     * @return $this
     */
    public function setArgumentTypes(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->argument_types = $arr;

        return $this;
    }

}

