<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query.proto

namespace Stargate;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>stargate.StreamingResponse</code>
 */
class StreamingResponse extends \Google\Protobuf\Internal\Message
{
    protected $message;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Stargate\Response $response
     *     @type \Google\Rpc\Status $status
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.stargate.Response response = 1;</code>
     * @return \Stargate\Response|null
     */
    public function getResponse()
    {
        return $this->readOneof(1);
    }

    public function hasResponse()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.stargate.Response response = 1;</code>
     * @param \Stargate\Response $var
     * @return $this
     */
    public function setResponse(\Stargate\Response|null $var)
    {
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.rpc.Status status = 2;</code>
     * @return \Google\Rpc\Status|null
     */
    public function getStatus()
    {
        return $this->readOneof(2);
    }

    public function hasStatus()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.google.rpc.Status status = 2;</code>
     * @param \Google\Rpc\Status $var
     * @return $this
     */
    public function setStatus(\Google\Rpc\Status|null $var)
    {
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getMessage()
    {
        return $this->whichOneof("message");
    }

}

