<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query.proto

namespace Stargate;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Tracing information, included in the Response when it was requested by the client (see
 * QueryParameters.tracing or BatchParameters.tracing)
 *
 * Generated from protobuf message <code>stargate.Traces</code>
 */
class Traces extends \Google\Protobuf\Internal\Message
{
    /**
     * A technical identifier for this trace.
     *
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * The server-side duration of the query (in microseconds).
     *
     * Generated from protobuf field <code>int64 duration = 2;</code>
     */
    protected $duration = 0;
    /**
     * The server-side timestamp of the start of the query.
     *
     * Generated from protobuf field <code>int64 started_at = 3;</code>
     */
    protected $started_at = 0;
    /**
     * Generated from protobuf field <code>repeated .stargate.Traces.Event events = 4;</code>
     */
    private $events;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           A technical identifier for this trace.
     *     @type int|string $duration
     *           The server-side duration of the query (in microseconds).
     *     @type int|string $started_at
     *           The server-side timestamp of the start of the query.
     *     @type \Stargate\Traces\Event[] $events
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * A technical identifier for this trace.
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * A technical identifier for this trace.
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->id = $var;

        return $this;
    }

    /**
     * The server-side duration of the query (in microseconds).
     *
     * Generated from protobuf field <code>int64 duration = 2;</code>
     * @return int|string
     */
    public function getDuration()
    {
        return $this->duration;
    }

    /**
     * The server-side duration of the query (in microseconds).
     *
     * Generated from protobuf field <code>int64 duration = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDuration(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->duration = $var;

        return $this;
    }

    /**
     * The server-side timestamp of the start of the query.
     *
     * Generated from protobuf field <code>int64 started_at = 3;</code>
     * @return int|string
     */
    public function getStartedAt()
    {
        return $this->started_at;
    }

    /**
     * The server-side timestamp of the start of the query.
     *
     * Generated from protobuf field <code>int64 started_at = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartedAt(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->started_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .stargate.Traces.Event events = 4;</code>
     * @return RepeatedField<\Stargate\Traces\Event>
     */
    public function getEvents()
    {
        return $this->events;
    }

    /**
     * Generated from protobuf field <code>repeated .stargate.Traces.Event events = 4;</code>
     * @param \Stargate\Traces\Event[] $var
     * @return $this
     */
    public function setEvents(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Stargate\Traces\Event::class);
        $this->events = $arr;

        return $this;
    }

}

