<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query.proto

namespace Stargate;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * A CQL column type.
 *
 * Generated from protobuf message <code>stargate.TypeSpec</code>
 */
class TypeSpec extends \Google\Protobuf\Internal\Message
{
    protected $spec;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $basic
     *     @type \Stargate\TypeSpec\Map $map
     *     @type \Stargate\TypeSpec\PBList $list
     *     @type \Stargate\TypeSpec\Set $set
     *     @type \Stargate\TypeSpec\Udt $udt
     *     @type \Stargate\TypeSpec\Tuple $tuple
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.stargate.TypeSpec.Basic basic = 1;</code>
     * @return int one of the values in {@see \Stargate\TypeSpec\Basic}
     */
    public function getBasic()
    {
        return $this->readOneof(1);
    }

    public function hasBasic()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.stargate.TypeSpec.Basic basic = 1;</code>
     * @param int $var one of the values in {@see \Stargate\TypeSpec\Basic}
     * @return $this
     */
    public function setBasic(int $var)
    {
        GPBUtil::checkEnum($var, \Stargate\TypeSpec\Basic::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.stargate.TypeSpec.Map map = 2;</code>
     * @return \Stargate\TypeSpec\Map|null
     */
    public function getMap()
    {
        return $this->readOneof(2);
    }

    public function hasMap()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.stargate.TypeSpec.Map map = 2;</code>
     * @param \Stargate\TypeSpec\Map $var
     * @return $this
     */
    public function setMap(\Stargate\TypeSpec\Map|null $var)
    {
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.stargate.TypeSpec.List list = 3;</code>
     * @return \Stargate\TypeSpec\PBList|null
     */
    public function getList()
    {
        return $this->readOneof(3);
    }

    public function hasList()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.stargate.TypeSpec.List list = 3;</code>
     * @param \Stargate\TypeSpec\PBList $var
     * @return $this
     */
    public function setList(\Stargate\TypeSpec\PBList|null $var)
    {
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.stargate.TypeSpec.Set set = 4;</code>
     * @return \Stargate\TypeSpec\Set|null
     */
    public function getSet()
    {
        return $this->readOneof(4);
    }

    public function hasSet()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.stargate.TypeSpec.Set set = 4;</code>
     * @param \Stargate\TypeSpec\Set $var
     * @return $this
     */
    public function setSet(\Stargate\TypeSpec\Set|null $var)
    {
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.stargate.TypeSpec.Udt udt = 5;</code>
     * @return \Stargate\TypeSpec\Udt|null
     */
    public function getUdt()
    {
        return $this->readOneof(5);
    }

    public function hasUdt()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>.stargate.TypeSpec.Udt udt = 5;</code>
     * @param \Stargate\TypeSpec\Udt $var
     * @return $this
     */
    public function setUdt(\Stargate\TypeSpec\Udt|null $var)
    {
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.stargate.TypeSpec.Tuple tuple = 6;</code>
     * @return \Stargate\TypeSpec\Tuple|null
     */
    public function getTuple()
    {
        return $this->readOneof(6);
    }

    public function hasTuple()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>.stargate.TypeSpec.Tuple tuple = 6;</code>
     * @param \Stargate\TypeSpec\Tuple $var
     * @return $this
     */
    public function setTuple(\Stargate\TypeSpec\Tuple|null $var)
    {
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getSpec()
    {
        return $this->whichOneof("spec");
    }

}

