<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query.proto

namespace Stargate;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Thrown when the coordinator knows there is not enough replicas alive to perform a query with the
 * requested consistency level.
 *
 * Generated from protobuf message <code>stargate.Unavailable</code>
 */
class Unavailable extends \Google\Protobuf\Internal\Message
{
    /**
     * The consistency level of the operation that failed.
     *
     * Generated from protobuf field <code>.stargate.Consistency consistency = 1;</code>
     */
    protected $consistency = 0;
    /**
     * The number of replica acknowledgements/responses required to perform the operation (with its
     * required consistency level).
     *
     * Generated from protobuf field <code>int32 required = 2;</code>
     */
    protected $required = 0;
    /**
     * The number of replicas that were known to be alive by the coordinator node when it tried to
     * execute the operation.
     *
     * Generated from protobuf field <code>int32 alive = 3;</code>
     */
    protected $alive = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $consistency
     *           The consistency level of the operation that failed.
     *     @type int $required
     *           The number of replica acknowledgements/responses required to perform the operation (with its
     *           required consistency level).
     *     @type int $alive
     *           The number of replicas that were known to be alive by the coordinator node when it tried to
     *           execute the operation.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * The consistency level of the operation that failed.
     *
     * Generated from protobuf field <code>.stargate.Consistency consistency = 1;</code>
     * @return int one of the values in {@see \Stargate\Consistency}
     */
    public function getConsistency()
    {
        return $this->consistency;
    }

    /**
     * The consistency level of the operation that failed.
     *
     * Generated from protobuf field <code>.stargate.Consistency consistency = 1;</code>
     * @param int $var one of the values in {@see \Stargate\Consistency}
     * @return $this
     */
    public function setConsistency(int $var)
    {
        GPBUtil::checkEnum($var, \Stargate\Consistency::class);
        $this->consistency = $var;

        return $this;
    }

    /**
     * The number of replica acknowledgements/responses required to perform the operation (with its
     * required consistency level).
     *
     * Generated from protobuf field <code>int32 required = 2;</code>
     * @return int
     */
    public function getRequired()
    {
        return $this->required;
    }

    /**
     * The number of replica acknowledgements/responses required to perform the operation (with its
     * required consistency level).
     *
     * Generated from protobuf field <code>int32 required = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setRequired(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->required = $var;

        return $this;
    }

    /**
     * The number of replicas that were known to be alive by the coordinator node when it tried to
     * execute the operation.
     *
     * Generated from protobuf field <code>int32 alive = 3;</code>
     * @return int
     */
    public function getAlive()
    {
        return $this->alive;
    }

    /**
     * The number of replicas that were known to be alive by the coordinator node when it tried to
     * execute the operation.
     *
     * Generated from protobuf field <code>int32 alive = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setAlive(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->alive = $var;

        return $this;
    }

}

