<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query.proto

namespace Stargate;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * The values to bind to the placeholders in a query.
 *
 * Generated from protobuf message <code>stargate.Values</code>
 */
class Values extends \Google\Protobuf\Internal\Message
{
    /**
     * The values.
     *
     * Generated from protobuf field <code>repeated .stargate.Value values = 1;</code>
     */
    private $values;
    /**
     * The value names, if the query uses named placeholders.
     *
     * Generated from protobuf field <code>repeated string value_names = 2;</code>
     */
    private $value_names;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Stargate\Value[] $values
     *           The values.
     *     @type string[] $value_names
     *           The value names, if the query uses named placeholders.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * The values.
     *
     * Generated from protobuf field <code>repeated .stargate.Value values = 1;</code>
     * @return RepeatedField<\Stargate\Value>
     */
    public function getValues()
    {
        return $this->values;
    }

    /**
     * The values.
     *
     * Generated from protobuf field <code>repeated .stargate.Value values = 1;</code>
     * @param \Stargate\Value[] $var
     * @return $this
     */
    public function setValues(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Stargate\Value::class);
        $this->values = $arr;

        return $this;
    }

    /**
     * The value names, if the query uses named placeholders.
     *
     * Generated from protobuf field <code>repeated string value_names = 2;</code>
     * @return RepeatedField<string>
     */
    public function getValueNames()
    {
        return $this->value_names;
    }

    /**
     * The value names, if the query uses named placeholders.
     *
     * Generated from protobuf field <code>repeated string value_names = 2;</code>
     * @param string[] $var
     * @return $this
     */
    public function setValueNames(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->value_names = $arr;

        return $this;
    }

}

