<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query.proto

namespace Stargate;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * A CQL value. This is used both in requests to bind parameterized query strings, and in responses
 * to represent the result data.
 *
 * Generated from protobuf message <code>stargate.Value</code>
 */
class Value extends \Google\Protobuf\Internal\Message
{
    protected $inner;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Stargate\Value\PBNull $null
     *           The CQL value NULL.
     *     @type \Stargate\Value\PBUnset $unset
     *           An unset value.
     *           This can only be used for bind values in requests.
     *     @type int|string $int
     *           CQL types: tinyint, smallint, int, bigint, counter, timestamp
     *     @type float $float
     *           CQL types: float
     *     @type float $double
     *           CQL types: double
     *     @type bool $boolean
     *           CQL types: boolean
     *     @type string $string
     *           CQL types: ascii, varchar, text
     *     @type string $bytes
     *           CQL types: blob, custom
     *     @type \Stargate\Inet $inet
     *           CQL types: inet
     *     @type \Stargate\Uuid $uuid
     *           CQL types: uuid, timeuuid
     *     @type int $date
     *           CQL types: date
     *           An unsigned integer representing days with Unix epoch (January, 1 1970) at 2^31.
     *           Examples:
     *           0:    -5877641-06-23
     *           2^31: 1970-1-1
     *           2^32: 5881580-07-11
     *     @type int|string $time
     *           CQL types: time
     *           An unsigned integer representing the number of nanoseconds since midnight. Valid values are
     *           in the range 0 to 86399999999999 (inclusive).
     *     @type \Stargate\Duration $duration
     *           CQL types: duration
     *     @type \Stargate\Collection $collection
     *           CQL types: list, set, map, tuple
     *     @type \Stargate\UdtValue $udt
     *           CQL types: user defined types
     *     @type \Stargate\Varint $varint
     *           CQL types: varint
     *     @type \Stargate\Decimal $decimal
     *           CQL types: decimal
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * The CQL value NULL.
     *
     * Generated from protobuf field <code>.stargate.Value.Null null = 1;</code>
     * @return \Stargate\Value\PBNull|null
     */
    public function getNull()
    {
        return $this->readOneof(1);
    }

    public function hasNull()
    {
        return $this->hasOneof(1);
    }

    /**
     * The CQL value NULL.
     *
     * Generated from protobuf field <code>.stargate.Value.Null null = 1;</code>
     * @param \Stargate\Value\PBNull $var
     * @return $this
     */
    public function setNull(\Stargate\Value\PBNull|null $var)
    {
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * An unset value.
     * This can only be used for bind values in requests.
     *
     * Generated from protobuf field <code>.stargate.Value.Unset unset = 2;</code>
     * @return \Stargate\Value\PBUnset|null
     */
    public function getUnset()
    {
        return $this->readOneof(2);
    }

    public function hasUnset()
    {
        return $this->hasOneof(2);
    }

    /**
     * An unset value.
     * This can only be used for bind values in requests.
     *
     * Generated from protobuf field <code>.stargate.Value.Unset unset = 2;</code>
     * @param \Stargate\Value\PBUnset $var
     * @return $this
     */
    public function setUnset(\Stargate\Value\PBUnset|null $var)
    {
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * CQL types: tinyint, smallint, int, bigint, counter, timestamp
     *
     * Generated from protobuf field <code>sint64 int = 3;</code>
     * @return int|string
     */
    public function getInt()
    {
        return $this->readOneof(3);
    }

    public function hasInt()
    {
        return $this->hasOneof(3);
    }

    /**
     * CQL types: tinyint, smallint, int, bigint, counter, timestamp
     *
     * Generated from protobuf field <code>sint64 int = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setInt(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * CQL types: float
     *
     * Generated from protobuf field <code>float float = 4;</code>
     * @return float
     */
    public function getFloat()
    {
        return $this->readOneof(4);
    }

    public function hasFloat()
    {
        return $this->hasOneof(4);
    }

    /**
     * CQL types: float
     *
     * Generated from protobuf field <code>float float = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setFloat(float $var)
    {
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * CQL types: double
     *
     * Generated from protobuf field <code>double double = 5;</code>
     * @return float
     */
    public function getDouble()
    {
        return $this->readOneof(5);
    }

    public function hasDouble()
    {
        return $this->hasOneof(5);
    }

    /**
     * CQL types: double
     *
     * Generated from protobuf field <code>double double = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setDouble(float $var)
    {
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * CQL types: boolean
     *
     * Generated from protobuf field <code>bool boolean = 6;</code>
     * @return bool
     */
    public function getBoolean()
    {
        return $this->readOneof(6);
    }

    public function hasBoolean()
    {
        return $this->hasOneof(6);
    }

    /**
     * CQL types: boolean
     *
     * Generated from protobuf field <code>bool boolean = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setBoolean(bool $var)
    {
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * CQL types: ascii, varchar, text
     *
     * Generated from protobuf field <code>string string = 7;</code>
     * @return string
     */
    public function getString()
    {
        return $this->readOneof(7);
    }

    public function hasString()
    {
        return $this->hasOneof(7);
    }

    /**
     * CQL types: ascii, varchar, text
     *
     * Generated from protobuf field <code>string string = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setString(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * CQL types: blob, custom
     *
     * Generated from protobuf field <code>bytes bytes = 8;</code>
     * @return string
     */
    public function getBytes()
    {
        return $this->readOneof(8);
    }

    public function hasBytes()
    {
        return $this->hasOneof(8);
    }

    /**
     * CQL types: blob, custom
     *
     * Generated from protobuf field <code>bytes bytes = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setBytes(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->writeOneof(8, $var);

        return $this;
    }

    /**
     * CQL types: inet
     *
     * Generated from protobuf field <code>.stargate.Inet inet = 9;</code>
     * @return \Stargate\Inet|null
     */
    public function getInet()
    {
        return $this->readOneof(9);
    }

    public function hasInet()
    {
        return $this->hasOneof(9);
    }

    /**
     * CQL types: inet
     *
     * Generated from protobuf field <code>.stargate.Inet inet = 9;</code>
     * @param \Stargate\Inet $var
     * @return $this
     */
    public function setInet(\Stargate\Inet|null $var)
    {
        $this->writeOneof(9, $var);

        return $this;
    }

    /**
     * CQL types: uuid, timeuuid
     *
     * Generated from protobuf field <code>.stargate.Uuid uuid = 10;</code>
     * @return \Stargate\Uuid|null
     */
    public function getUuid()
    {
        return $this->readOneof(10);
    }

    public function hasUuid()
    {
        return $this->hasOneof(10);
    }

    /**
     * CQL types: uuid, timeuuid
     *
     * Generated from protobuf field <code>.stargate.Uuid uuid = 10;</code>
     * @param \Stargate\Uuid $var
     * @return $this
     */
    public function setUuid(\Stargate\Uuid|null $var)
    {
        $this->writeOneof(10, $var);

        return $this;
    }

    /**
     * CQL types: date
     * An unsigned integer representing days with Unix epoch (January, 1 1970) at 2^31.
     * Examples:
     * 0:    -5877641-06-23
     * 2^31: 1970-1-1
     * 2^32: 5881580-07-11
     *
     * Generated from protobuf field <code>uint32 date = 11;</code>
     * @return int
     */
    public function getDate()
    {
        return $this->readOneof(11);
    }

    public function hasDate()
    {
        return $this->hasOneof(11);
    }

    /**
     * CQL types: date
     * An unsigned integer representing days with Unix epoch (January, 1 1970) at 2^31.
     * Examples:
     * 0:    -5877641-06-23
     * 2^31: 1970-1-1
     * 2^32: 5881580-07-11
     *
     * Generated from protobuf field <code>uint32 date = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setDate(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->writeOneof(11, $var);

        return $this;
    }

    /**
     * CQL types: time
     * An unsigned integer representing the number of nanoseconds since midnight. Valid values are
     * in the range 0 to 86399999999999 (inclusive).
     *
     * Generated from protobuf field <code>uint64 time = 12;</code>
     * @return int|string
     */
    public function getTime()
    {
        return $this->readOneof(12);
    }

    public function hasTime()
    {
        return $this->hasOneof(12);
    }

    /**
     * CQL types: time
     * An unsigned integer representing the number of nanoseconds since midnight. Valid values are
     * in the range 0 to 86399999999999 (inclusive).
     *
     * Generated from protobuf field <code>uint64 time = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTime(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->writeOneof(12, $var);

        return $this;
    }

    /**
     * CQL types: duration
     *
     * Generated from protobuf field <code>.stargate.Duration duration = 17;</code>
     * @return \Stargate\Duration|null
     */
    public function getDuration()
    {
        return $this->readOneof(17);
    }

    public function hasDuration()
    {
        return $this->hasOneof(17);
    }

    /**
     * CQL types: duration
     *
     * Generated from protobuf field <code>.stargate.Duration duration = 17;</code>
     * @param \Stargate\Duration $var
     * @return $this
     */
    public function setDuration(\Stargate\Duration|null $var)
    {
        $this->writeOneof(17, $var);

        return $this;
    }

    /**
     * CQL types: list, set, map, tuple
     *
     * Generated from protobuf field <code>.stargate.Collection collection = 13;</code>
     * @return \Stargate\Collection|null
     */
    public function getCollection()
    {
        return $this->readOneof(13);
    }

    public function hasCollection()
    {
        return $this->hasOneof(13);
    }

    /**
     * CQL types: list, set, map, tuple
     *
     * Generated from protobuf field <code>.stargate.Collection collection = 13;</code>
     * @param \Stargate\Collection $var
     * @return $this
     */
    public function setCollection(\Stargate\Collection|null $var)
    {
        $this->writeOneof(13, $var);

        return $this;
    }

    /**
     * CQL types: user defined types
     *
     * Generated from protobuf field <code>.stargate.UdtValue udt = 14;</code>
     * @return \Stargate\UdtValue|null
     */
    public function getUdt()
    {
        return $this->readOneof(14);
    }

    public function hasUdt()
    {
        return $this->hasOneof(14);
    }

    /**
     * CQL types: user defined types
     *
     * Generated from protobuf field <code>.stargate.UdtValue udt = 14;</code>
     * @param \Stargate\UdtValue $var
     * @return $this
     */
    public function setUdt(\Stargate\UdtValue|null $var)
    {
        $this->writeOneof(14, $var);

        return $this;
    }

    /**
     * CQL types: varint
     *
     * Generated from protobuf field <code>.stargate.Varint varint = 15;</code>
     * @return \Stargate\Varint|null
     */
    public function getVarint()
    {
        return $this->readOneof(15);
    }

    public function hasVarint()
    {
        return $this->hasOneof(15);
    }

    /**
     * CQL types: varint
     *
     * Generated from protobuf field <code>.stargate.Varint varint = 15;</code>
     * @param \Stargate\Varint $var
     * @return $this
     */
    public function setVarint(\Stargate\Varint|null $var)
    {
        $this->writeOneof(15, $var);

        return $this;
    }

    /**
     * CQL types: decimal
     *
     * Generated from protobuf field <code>.stargate.Decimal decimal = 16;</code>
     * @return \Stargate\Decimal|null
     */
    public function getDecimal()
    {
        return $this->readOneof(16);
    }

    public function hasDecimal()
    {
        return $this->hasOneof(16);
    }

    /**
     * CQL types: decimal
     *
     * Generated from protobuf field <code>.stargate.Decimal decimal = 16;</code>
     * @param \Stargate\Decimal $var
     * @return $this
     */
    public function setDecimal(\Stargate\Decimal|null $var)
    {
        $this->writeOneof(16, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getInner()
    {
        return $this->whichOneof("inner");
    }

}

