<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query.proto

namespace Stargate\SchemaChange;

use UnexpectedValueException;

/**
 * Protobuf type <code>stargate.SchemaChange.Target</code>
 */
class Target
{
    /**
     * Generated from protobuf enum <code>KEYSPACE = 0;</code>
     */
    const KEYSPACE = 0;
    /**
     * Generated from protobuf enum <code>TABLE = 1;</code>
     */
    const TABLE = 1;
    /**
     * Generated from protobuf enum <code>TYPE = 2;</code>
     */
    const TYPE = 2;
    /**
     * Generated from protobuf enum <code>FUNCTION = 3;</code>
     */
    const PBFUNCTION = 3;
    /**
     * Generated from protobuf enum <code>AGGREGATE = 4;</code>
     */
    const AGGREGATE = 4;

    private static $valueToName = [
        self::KEYSPACE => 'KEYSPACE',
        self::TABLE => 'TABLE',
        self::TYPE => 'TYPE',
        self::PBFUNCTION => 'FUNCTION',
        self::AGGREGATE => 'AGGREGATE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            $pbconst =  __CLASS__. '::PB' . strtoupper($name);
            if (!defined($pbconst)) {
                throw new UnexpectedValueException(sprintf(
                        'Enum %s has no value defined for name %s', __CLASS__, $name));
            }
            return constant($pbconst);
        }
        return constant($const);
    }
}

