<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query.proto

namespace Stargate\SchemaChange;

use UnexpectedValueException;

/**
 * Protobuf type <code>stargate.SchemaChange.Type</code>
 */
class Type
{
    /**
     * Generated from protobuf enum <code>CREATED = 0;</code>
     */
    const CREATED = 0;
    /**
     * Generated from protobuf enum <code>UPDATED = 1;</code>
     */
    const UPDATED = 1;
    /**
     * Generated from protobuf enum <code>DROPPED = 2;</code>
     */
    const DROPPED = 2;

    private static $valueToName = [
        self::CREATED => 'CREATED',
        self::UPDATED => 'UPDATED',
        self::DROPPED => 'DROPPED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

