<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query.proto

namespace Stargate\Traces;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * An event in a query trace.
 *
 * Generated from protobuf message <code>stargate.Traces.Event</code>
 */
class Event extends \Google\Protobuf\Internal\Message
{
    /**
     * Which activity the event corresponds to.
     *
     * Generated from protobuf field <code>string activity = 1;</code>
     */
    protected $activity = '';
    /**
     * Identifies the host having generated the event.
     *
     * Generated from protobuf field <code>string source = 2;</code>
     */
    protected $source = '';
    /**
     * The number of microseconds elapsed on the source when this event occurred since the moment
     * when the source started handling the query.
     *
     * Generated from protobuf field <code>int64 source_elapsed = 3;</code>
     */
    protected $source_elapsed = 0;
    /**
     * The name of the server thread on which this event occurred.
     *
     * Generated from protobuf field <code>string thread = 4;</code>
     */
    protected $thread = '';
    /**
     * A technical identifier for the event.
     *
     * Generated from protobuf field <code>string event_id = 5;</code>
     */
    protected $event_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $activity
     *           Which activity the event corresponds to.
     *     @type string $source
     *           Identifies the host having generated the event.
     *     @type int|string $source_elapsed
     *           The number of microseconds elapsed on the source when this event occurred since the moment
     *           when the source started handling the query.
     *     @type string $thread
     *           The name of the server thread on which this event occurred.
     *     @type string $event_id
     *           A technical identifier for the event.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * Which activity the event corresponds to.
     *
     * Generated from protobuf field <code>string activity = 1;</code>
     * @return string
     */
    public function getActivity()
    {
        return $this->activity;
    }

    /**
     * Which activity the event corresponds to.
     *
     * Generated from protobuf field <code>string activity = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setActivity(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->activity = $var;

        return $this;
    }

    /**
     * Identifies the host having generated the event.
     *
     * Generated from protobuf field <code>string source = 2;</code>
     * @return string
     */
    public function getSource()
    {
        return $this->source;
    }

    /**
     * Identifies the host having generated the event.
     *
     * Generated from protobuf field <code>string source = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSource(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->source = $var;

        return $this;
    }

    /**
     * The number of microseconds elapsed on the source when this event occurred since the moment
     * when the source started handling the query.
     *
     * Generated from protobuf field <code>int64 source_elapsed = 3;</code>
     * @return int|string
     */
    public function getSourceElapsed()
    {
        return $this->source_elapsed;
    }

    /**
     * The number of microseconds elapsed on the source when this event occurred since the moment
     * when the source started handling the query.
     *
     * Generated from protobuf field <code>int64 source_elapsed = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSourceElapsed(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->source_elapsed = $var;

        return $this;
    }

    /**
     * The name of the server thread on which this event occurred.
     *
     * Generated from protobuf field <code>string thread = 4;</code>
     * @return string
     */
    public function getThread()
    {
        return $this->thread;
    }

    /**
     * The name of the server thread on which this event occurred.
     *
     * Generated from protobuf field <code>string thread = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setThread(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->thread = $var;

        return $this;
    }

    /**
     * A technical identifier for the event.
     *
     * Generated from protobuf field <code>string event_id = 5;</code>
     * @return string
     */
    public function getEventId()
    {
        return $this->event_id;
    }

    /**
     * A technical identifier for the event.
     *
     * Generated from protobuf field <code>string event_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setEventId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->event_id = $var;

        return $this;
    }

}

